fragment TeamFragment on TeamType {
  id
  color
  image
  name
}

fragment BoxScoreEntryFragment on BoxScoreEntryType {
  team
  period
  time
  description
  scorer
  assist
  scoreBy
  corScore
  oppScore
}

fragment GameFragment on GameType {
  id
  city
  date
  gender
  location
  opponentId
  result
  sport
  state
  time
  scoreBreakdown
  utcDate
  ticketLink
  team {
    ...TeamFragment
  }
  boxScore {
    ...BoxScoreEntryFragment
  }
}

query Games($limit: Int!, $offset: Int!) {
  games(limit: $limit, offset: $offset) {
    ...GameFragment
  }
}

query GamesByDate($startDate: DateTime!, $endDate: DateTime!) {
  gamesByDate(startDate: $startDate, endDate: $endDate) {
    ...GameFragment
  }
}
